services:
 digital-garden:
   image: obsidian-digital-garden:25-04-21
   volumes:
      - ./.env:/usr/src/app/.env
    # - ./src/site/_includes/components/user/notes/footer:/usr/src/app/src/site/_includes/components/user/notes/footer 
      - ./src/site/notes:/usr/src/app/src/site/notes
    # - ./dist:/usr/src/app/dist
      - ./src/site/img:/usr/src/app/src/site/img
    # - ./.eleventy.js:/usr/src/app/.eleventy.js
   ports:
     - "10034:8080"
   command: npm run dev
   environment:
     - NODE_ENV=development
