#!/bin/bash
awk '
/^\/\* ========================================================================/ {
    if (!inserted) {
        print "/* ========================================================================"
        print "   1.5. LUXURY APP SHELL (Grid Architecture)"
        print "   ======================================================================== */"
        print ".luxury-app-layout {"
        print "    display: grid;"
        print "    grid-template-columns: auto minmax(0, 1fr) auto;"
        print "    grid-template-areas: \"left main right\";"
        print "    gap: 2rem;"
        print "    min-height: 100vh;"
        print "    padding: 2rem;"
        print "    box-sizing: border-box;"
        print "    width: 100%;"
        print "    max-width: 100vw;"
        print "}"
        print ""
        print ".luxury-sidebar-left {"
        print "    grid-area: left;"
        print "    width: var(--sidebar-left-width);"
        print "    display: flex;"
        print "    flex-direction: column;"
        print "}"
        print ""
        print ".luxury-content-core {"
        print "    grid-area: main;"
        print "    min-width: 0; /* Critical for grid minmax child to not overflow */"
        print "    border-radius: 20px;"
        print "    background: transparent !important;"
        print "}"
        print ""
        print ".luxury-sidebar-right {"
        print "    grid-area: right;"
        print "    width: var(--sidebar-right-width);"
        print "    display: flex;"
        print "    flex-direction: column;"
        print "}"
        print ""
        print "/* Responsive Behavior */"
        print "@media (max-width: 1400px) {"
        print "    .luxury-sidebar-left { display: none; }"
        print "}"
        print ""
        print "@media (max-width: 1024px) {"
        print "    .luxury-app-layout {"
        print "        display: flex;"
        print "        flex-direction: column;"
        print "        padding: 1rem;"
        print "    }"
        print "    .luxury-sidebar-left, .luxury-sidebar-right { width: 100%; }"
        print "}"
        print ""
        inserted = 1
    }
}
{ print }
' src/site/styles/user/minimalist-theme.scss > temp.scss
mv temp.scss src/site/styles/user/minimalist-theme.scss
